{
  "relations":[
    {
      "templateName":"Dao.ftl",
      "fileName":"${entity+"Dao.java"}",
      "exportPath":"src/main/java/me/wangsheshan/exchange/dao/"
    },
    {
      "templateName":"Service.ftl",
      "fileName":"${entity+"Service.java"}",
      "exportPath":"src/main/java/me/wangsheshan/exchange/service/"
    },
    {
      "templateName":"ServiceImpl.ftl",
      "fileName":"${entity+"ServiceImpl.java"}",
      "exportPath":"src/main/java/me/wangsheshan/exchange/service/impl/"
    }
  ]
}