{
  "relations":[
    {
      "templateName":"Dao.ftl",
      "fileName":"${entity+"Dao.java"}",
      "exportPath":"src/main/java/com/andlinks/dao/"
    },
    {
      "templateName":"Service.ftl",
      "fileName":"${entity+"Service.java"}",
      "exportPath":"src/main/java/com/andlinks/service/"
    },
    {
      "templateName":"ServiceImpl.ftl",
      "fileName":"${entity+"ServiceImpl.java"}",
      "exportPath":"src/main/java/com/andlinks/service/impl/"
    }
  ]
}